version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: tvs
      POSTGRES_USER: tvs
      POSTGRES_PASSWORD: tvs
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tvs"]
      interval: 30s
      timeout: 10s
      retries: 3

  tvs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://tvs:tvs@postgres:5432/tvs?sslmode=disable
      - SERVER_ENVIRONMENT=development
      - EXTERNAL_SERVICES_INDEXING_ENGINE_BASE_URL=http://indexing-engine:8081
      - EXTERNAL_SERVICES_PDM_BASE_URL=http://pdm:8082
    volumes:
      - ./configs:/root/configs:ro

  # Mock Indexing Engine service for testing
  mock-ie:
    image: mockserver/mockserver:5.15.0
    ports:
      - "8081:1080"
    environment:
      MOCKSERVER_SERVER_PORT: 1080
      MOCKSERVER_LOG_LEVEL: INFO

  # Mock PDM service for testing
  mock-pdm:
    image: mockserver/mockserver:5.15.0
    ports:
      - "8082:1080"
    environment:
      MOCKSERVER_SERVER_PORT: 1080
      MOCKSERVER_LOG_LEVEL: INFO

volumes:
  postgres_data: