version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: wms_user
      POSTGRES_PASSWORD: wms_password
      POSTGRES_DB: wms_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wms_user -d wms_db"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - wms-network

  tvs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./configs:/root/configs:ro
    networks:
      - wms-network

volumes:
  postgres_data:
    driver: local

networks:
  wms-network:
    driver: bridge
